# Generated by Django 3.1.1 on 2020-10-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
