# Generated by Django 3.1.1 on 2020-10-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20201005_2216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
