// For login
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
// For registration
export const REGISTRATION_START = "REGISTRATION_START";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";
// Todos
export const TODOS_REQUEST = "GET_TODOS_REQUEST";
export const TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const TODOS_FAILURE = "GET_TODOS_FAILURE";
export const TODO_CREATED = "TODO_CREATED";
export const GET_SELECTED_TODO = "GET_SELECTED_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
